theme: jekyll-theme-minimal
title: Welcome to TAMU Group 1's homepage!
Description: This is Group 1's project page for TCMG 412! 
url: https://tamugroup1.github.io/pelicangroup1
markdown: kramdown
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
